apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: basic-notebook
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: basic-notebook
        image: kubeflownotebookswg/jupyter-scipy:latest
        resources:
          requests:
            cpu: "1.0"
            memory: 2Gi
          limits:
            cpu: "2.0"
            memory: 4Gi
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: basic-notebook-workspace

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basic-notebook-workspace
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


