apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: tensorflow-notebook
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: tensorflow-notebook
        image: kubeflownotebookswg/jupyter-tensorflow-full:latest
        resources:
          requests:
            cpu: "2.0"
            memory: 4Gi
          limits:
            cpu: "2.0"
            memory: 4Gi
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: tensorflow-notebook-workspace

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tensorflow-notebook-workspace
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi


